### PR TITLE
fix: bug in segcache cas implementation

### LINKED ISSUE #59: Segcache integration test is flaky within MacOS CI
The segcache integration test regularly fails for unrelated PRs in CI. #58 has marked this test as ignored. Once this issue is resolved that should be removed.

The test failure tends to look like this
```
2023-02-06T15:24:31.495+00:00 INFO [admin] running admin on: 127.0.0.1:9999
2023-02-06T15:24:31.495+00:00 INFO [server::listener] running server on: 0.0.0.0:12321

2023-02-06T15:24:41.584+00:00 INFO [integration::common] testing: get miss
2023-02-06T15:24:41.586+00:00 INFO [integration::common] status: passed

2023-02-06T15:24:41.586+00:00 INFO [integration::common] testing: gets miss
2023-02-06T15:24:41.667+00:00 INFO [integration::common] status: passed

2023-02-06T15:24:41.667+00:00 INFO [integration::common] testing: set and get
2023-02-06T15:24:41.888+00:00 INFO [integration::common] status: passed

2023-02-06T15:24:41.888+00:00 INFO [integration::common] testing: cas not_found
2023-02-06T15:24:41.990+00:00 INFO [integration::common] status: passed

2023-02-06T15:24:41.990+00:00 INFO [integration::common] testing: cas exists
2023-02-06T15:24:42.433+00:00 INFO [integration::common] status: passed

2023-02-06T15:24:42.433+00:00 INFO [integration::common] testing: cas stored
2023-02-06T15:24:42.653+00:00 ERROR [integration::common] expected: [86, 65, 76, 85, 69, 32, 52, 32, 48, 32, 49, 13, 10, 48, 13, 10, 69, 78, 68, 13, 10]
2023-02-06T15:24:42.653+00:00 ERROR [integration::common] received: [69, 78, 68, 13, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
thread 'main' panicked at 'status: failed
', src/server/segcache/tests/common.rs:249:17
stack backtrace:
   0:        0x106555d08 - std::backtrace_rs::backtrace::libunwind::trace::h310cbd77a7d2ae59
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:        0x106555d08 - std::backtrace_rs::backtrace::trace_unsynchronized::h5768bae568840507
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x106555d08 - std::sys_common::backtrace::_print_fmt::hd104a205649a2ffb
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/sys_common/backtrace.rs:65:5
   3:        0x106555d08 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h521420ec33f3769d
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/sys_common/backtrace.rs:44:22
   4:        0x1064d829a - core::fmt::write::h694a0d7c23f57ada
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/fmt/mod.rs:1208:17
   5:        0x10652f92c - std::io::Write::write_fmt::h1920a3973ad439e5
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/io/mod.rs:1682:15
   6:        0x106559baa - std::sys_common::backtrace::_print::h75582c4ed1a04abb
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/sys_common/backtrace.rs:47:5
   7:        0x106559baa - std::sys_common::backtrace::print::hef1aa4dbdc07ee06
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/sys_common/backtrace.rs:34:9
   8:        0x1065597d3 - std::panicking::default_hook::{{closure}}::h529701a1070b4ce0
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:267:22
   9:        0x10655a820 - std::panicking::default_hook::hfeeab2c667b2d7c2
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:286:9
  10:        0x10655a820 - std::panicking::rust_panic_with_hook::h1b5245192f90251d
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:688:13
  11:        0x10655a2e8 - std::panicking::begin_panic_handler::{{closure}}::h3658f3a9566379d4
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:577:13
  12:        0x10655a278 - std::sys_common::backtrace::__rust_end_short_backtrace::h9e01645d962f8882
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/sys_common/backtrace.rs:137:18
  13:        0x10655a242 - rust_begin_unwind
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:575:5
  14:        0x1066725b3 - core::panicking::panic_fmt::h0097ad8ec0b07517
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/panicking.rs:64:14
  15:        0x1064b91b2 - integration::common::test::h11d917b82d2bf915
  16:        0x1064b9a68 - integration::common::tests::hc09557e5b6bd7830
                               at /Users/runner/work/pelikan/pelikan/src/server/segcache/tests/common.rs:56:5
  17:        0x1064b9a68 - integration::main::hc13071f0434bfd2d
                               at /Users/runner/work/pelikan/pelikan/src/server/segcache/tests/integration.rs:28:5
  18:        0x1064b6826 - core::ops::function::FnOnce::call_once::h5eb64975d91e601d
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/ops/function.rs:507:5
  19:        0x1064b6826 - std::sys_common::backtrace::__rust_begin_short_backtrace::h5a471b2b99bf64a3
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/sys_common/backtrace.rs:121:18
  20:        0x1064bbf9c - _main
  ```

### PR DESCRIPTION
**Pull request by hderms**
fixes #59 

Pretty sure this is the cause of the flakiness because if you set:

```
diff --git a/src/server/segcache/tests/common.rs b/src/server/segcache/tests/common.rs
index 9f33681..e551a35 100644
--- a/src/server/segcache/tests/common.rs
+++ b/src/server/segcache/tests/common.rs
@@ -235,7 +235,7 @@ fn test(name: &str, data: &[(&str, Option<&str>)]) {
             }
         }

-        std::thread::sleep(Duration::from_millis(10));
+        std::thread::sleep(Duration::from_millis(1000));
         let mut buf = vec![0; 4096];

         if let Some(response) = response {
```

so you enforce a long wait in between running commands, then the test will fail every time on my machine (x86_64 Ubuntu WSL2). 

I think the reason it doesn't fail all the time is due to machine load/architecture performance differences that cause the GET to occur either before or after the relatively immediate expiration of the key. If Pelikan was slower we'd probably have found this bug already.

The test that specifically fails (or at least the one that seems to be the cause of the nondeterministic failures) is here:
https://github.com/pelikan-io/pelikan/blob/4599e5f964ae59113e0d26e0a7ededcd46e9e4b0/src/server/segcache/tests/common.rs#L56-L66

If I run that sequence of commands on memcached, the `get` command will always succeed, regardless of how much time has passed. 

However, when I run those commands against `segcache`, the key is expired by the time I try to `get` it (at least that's the likely behavior I see, based on the GET returning nothing)

### CODE REVIEW

**Comment by swlynch99** [comment]
To check this in CI can you revert #58 here as well? It won't give 100% certainty but at least if that test fails then we know the issue is still there.

**Comment by hderms** [comment]
> To check this in CI can you revert #58 here as well? It won't give 100% certainty but at least if that test fails then we know the issue is still there.

ok I reverted it as part of this PR

**Comment by brayniac** [comment]
Per discussion on discord... this is actually a little more buggy than it appeared. Will edit the diff

**Review by swlynch99 — APPROVED** [review]
The code LGTM. I don't know enough to know if this is the best way to do things but it seems good to me.

File: src/entrystore/src/seg/memcache.rs [hunk 1]
```diff
@@ -285,19 +285,34 @@ impl Storage for Seg {
...
+        // a TTL of zero maps to the longest TTL representable which
+        // is ~97 days.
+
+        let ttl = cas.ttl().get().unwrap_or(0);
+
+        // Since we allow specifying Unix timestamps as TTLs, we can actually
+        // make a request that says that if the CAS value matches, the item
+        // should be immediately expired.
+        //
+        // However, we cannot check the CAS value without attempting to store,
```
Comment (thinkingfish) [inline src/entrystore/src/seg/memcache.rs:298]: The behavior about Unix timestamp isn't unique to cas, right? So if we have a `set` or `replace` command, it could also be that we should immediately delete the key from underlying storage. Today we handle them individually in the `memcache` entrystore implementation. However, now I wonder if the better place to deal with that is actually in `fn insert` in the seg module. Basically, if we handle `ttl == 0` as delete, and collapse `ttl <= 0` to `ttl == 0`, we can keep the data type signature but also simplify the entrystore implementation.

Comment (brayniac) [reply src/entrystore/src/seg/memcache.rs:298]: That's a legit critique. Can look at making that change

Comment (hderms) [reply src/entrystore/src/seg/memcache.rs:298]: we should probably merge this PR first if we think it's not risky because we're left with the choice of either failing builds non-deterministically or not running integration tests in CI

**Review by thinkingfish — APPROVED** [review]
